'use client';

import React, { useState } from 'react';
import { ArrowRight, Clock, FileText, Zap, CheckCircle, Star, MessageSquare, Shield } from 'lucide-react';
import { Button } from '@/components/ui/button';
import ChatBot from '@/components/ChatBot/ChatBot';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export default function SprintRequestPage() {
  const [isChatOpen, setIsChatOpen] = useState(false);

  const generateSamplePDF = () => {
    // Generate a sample PDF using jsPDF
    import('jspdf').then(({ default: jsPDF }) => {
      const doc = new jsPDF();
      let yPosition = 30;
      
      // Header
      doc.setFontSize(24);
      doc.setTextColor(37, 99, 235);
      doc.text('Sample Project Scope Document', 20, yPosition);
      
      yPosition += 10;
      doc.setFontSize(12);
      doc.setTextColor(100, 100, 100);
      doc.text('Generated by Kenkai Labs AI Assistant', 20, yPosition);
      
      yPosition += 7;
      doc.text('This is a sample document showing what you will receive', 20, yPosition);
      
      yPosition += 8;
      doc.setDrawColor(200, 200, 200);
      doc.line(20, yPosition, 190, yPosition);
      
      // Executive Summary
      yPosition += 15;
      doc.setFontSize(16);
      doc.setTextColor(37, 99, 235);
      doc.text('Executive Summary', 20, yPosition);
      
      yPosition += 10;
      doc.setFontSize(10);
      doc.setTextColor(60, 60, 60);
      const summary = doc.splitTextToSize(
        'This sample demonstrates our AI-powered requirements discovery output. Based on your conversation with our AI assistant, we generate a comprehensive scope document that includes project overview, technical architecture, deliverables, implementation phases, success metrics, and strategic recommendations.',
        170
      );
      doc.text(summary, 20, yPosition);
      yPosition += 5 * summary.length + 10;
      
      // Project Overview
      doc.setFontSize(14);
      doc.setTextColor(0, 0, 0);
      doc.text('1. Project Overview', 20, yPosition);
      yPosition += 8;
      
      doc.setFontSize(10);
      doc.setTextColor(60, 60, 60);
      doc.setFont('helvetica', 'bold');
      doc.text('Project Type:', 25, yPosition);
      doc.setFont('helvetica', 'normal');
      doc.text('E-commerce Platform', 70, yPosition);
      yPosition += 6;
      
      doc.setFont('helvetica', 'bold');
      doc.text('Business Objective:', 25, yPosition);
      doc.setFont('helvetica', 'normal');
      doc.text('Increase Revenue & Customer Engagement', 70, yPosition);
      yPosition += 6;
      
      doc.setFont('helvetica', 'bold');
      doc.text('Timeline:', 25, yPosition);
      doc.setFont('helvetica', 'normal');
      doc.text('3-4 months', 70, yPosition);
      yPosition += 6;
      
      doc.setFont('helvetica', 'bold');
      doc.text('Budget Range:', 25, yPosition);
      doc.setFont('helvetica', 'normal');
      doc.text('$50k-$100k', 70, yPosition);
      yPosition += 15;
      
      // Kenkai Labs Analysis
      doc.setFontSize(11);
      doc.setTextColor(37, 99, 235);
      doc.setFont('helvetica', 'bold');
      doc.text('Kenkai Labs Analysis:', 25, yPosition);
      yPosition += 6;
      
      doc.setFontSize(10);
      doc.setTextColor(60, 60, 60);
      doc.setFont('helvetica', 'normal');
      const analysis = doc.splitTextToSize(
        'E-commerce platforms require robust security, seamless payment processing, and optimized user experience. We recommend starting with core features (product catalog, secure checkout, order management) and scaling progressively. Mobile-first design is crucial as 65% of e-commerce traffic comes from mobile devices.',
        165
      );
      doc.text(analysis, 25, yPosition);
      yPosition += 5 * analysis.length + 10;
      
      // Technical Architecture
      doc.setFontSize(14);
      doc.setTextColor(0, 0, 0);
      doc.text('2. Recommended Tech Stack', 20, yPosition);
      yPosition += 8;
      
      doc.setFontSize(10);
      doc.setTextColor(60, 60, 60);
      
      const techStack = [
        { label: 'Frontend', value: 'Next.js 15 with TypeScript for type-safe development' },
        { label: 'Backend', value: 'Node.js API with Express or Next.js API routes' },
        { label: 'Database', value: 'PostgreSQL for products/orders, Redis for caching' },
        { label: 'Payments', value: 'Stripe for secure payment processing' },
        { label: 'Hosting', value: 'Vercel for frontend, AWS for backend services' }
      ];
      
      techStack.forEach(tech => {
        doc.setFont('helvetica', 'bold');
        doc.text(`${tech.label}:`, 25, yPosition);
        doc.setFont('helvetica', 'normal');
        yPosition += 5;
        const techText = doc.splitTextToSize(tech.value, 160);
        doc.text(techText, 25, yPosition);
        yPosition += 5 * techText.length + 3;
      });
      
      // Add new page
      doc.addPage();
      yPosition = 20;
      
      // Deliverables
      doc.setFontSize(14);
      doc.setTextColor(0, 0, 0);
      doc.text('3. Key Deliverables', 20, yPosition);
      yPosition += 8;
      
      doc.setFontSize(10);
      doc.setTextColor(60, 60, 60);
      
      const deliverables = [
        'Fully functional e-commerce platform',
        'Secure payment gateway integration',
        'Admin dashboard for inventory & orders',
        'Mobile-responsive design',
        'Product search & filtering',
        'User authentication & profiles',
        'Email notifications & receipts',
        'Analytics & reporting dashboard',
        'Documentation & training materials',
        '30 days post-launch support'
      ];
      
      deliverables.forEach((item, index) => {
        doc.text(`${index + 1}. ${item}`, 25, yPosition);
        yPosition += 6;
      });
      
      yPosition += 10;
      
      // Implementation Phases
      doc.setFontSize(14);
      doc.setTextColor(0, 0, 0);
      doc.text('4. Implementation Phases', 20, yPosition);
      yPosition += 8;
      
      doc.setFontSize(10);
      const phases = [
        { name: 'Discovery & Design', duration: '2 weeks', desc: 'Requirements, wireframes, and technical architecture' },
        { name: 'Core Development', duration: '8 weeks', desc: 'Product catalog, checkout, payment integration' },
        { name: 'Testing & QA', duration: '2 weeks', desc: 'Comprehensive testing and bug fixes' },
        { name: 'Launch & Support', duration: '1 week', desc: 'Deployment and post-launch monitoring' }
      ];
      
      phases.forEach(phase => {
        doc.setFont('helvetica', 'bold');
        doc.text(`${phase.name} (${phase.duration})`, 25, yPosition);
        doc.setFont('helvetica', 'normal');
        yPosition += 5;
        doc.text(phase.desc, 25, yPosition);
        yPosition += 8;
      });
      
      yPosition += 10;
      
      // Strategic Recommendations
      doc.setFontSize(14);
      doc.setTextColor(37, 99, 235);
      doc.text('Strategic Recommendations', 20, yPosition);
      yPosition += 8;
      
      doc.setFontSize(10);
      doc.setTextColor(60, 60, 60);
      
      const recommendations = [
        'Start with MVP to validate market fit, then iterate',
        'Implement comprehensive analytics from day one',
        'Prioritize mobile experience for higher conversions',
        'Use automated testing to maintain quality at scale',
        'Plan for scalability from architecture design phase'
      ];
      
      recommendations.forEach(rec => {
        const recText = doc.splitTextToSize(`• ${rec}`, 165);
        doc.text(recText, 25, yPosition);
        yPosition += 6 * recText.length;
      });
      
      // Footer
      yPosition = 270;
      doc.setFontSize(9);
      doc.setTextColor(150, 150, 150);
      doc.text('Kenkai Labs - From Problem Discovery to Product Launch', 20, yPosition);
      doc.text('Contact: hello@kenkailabs.com | www.kenkailabs.com', 20, yPosition + 5);
      
      // Save
      doc.save('Kenkai-Sample-Scope-Document.pdf');
    });
  };

  const features = [
    {
      icon: <MessageSquare className="w-6 h-6 text-blue-600" />,
      title: "Conversational Discovery",
      description: "AI guides you through questions to understand your exact needs"
    },
    {
      icon: <FileText className="w-6 h-6 text-green-600" />,
      title: "Instant Documentation",
      description: "Get a professional Scope of Work document in minutes"
    },
    {
      icon: <Clock className="w-6 h-6 text-purple-600" />,
      title: "Quick Turnaround",
      description: "From requirements to project start in 24-48 hours"
    },
    {
      icon: <Zap className="w-6 h-6 text-yellow-600" />,
      title: "Smart Recommendations",
      description: "AI suggests optimal tech stack and approach for your project"
    }
  ];

  const testimonials = [
    {
      name: "Rajesh Kumar",
      company: "TechStart India",
      rating: 5,
      text: "The AI chatbot helped us define our requirements so clearly. We got our project scope in 15 minutes!"
    },
    {
      name: "Priya Sharma",
      company: "E-commerce Plus",
      rating: 5,
      text: "Saved us weeks of back-and-forth meetings. The requirements document was spot-on."
    },
    {
      name: "Amit Patel",
      company: "FinTech Solutions",
      rating: 5,
      text: "The pricing transparency and instant documentation made decision-making so much easier."
    }
  ];

  const pricingPlans = [
    {
      name: "AI Scope Document",
      price: "FREE",
      period: "basic version",
      features: [
        "AI-guided requirement discovery",
        "Professional Scope of Work PDF",
        "Tech stack recommendations",
        "Timeline & phase breakdown",
        "Perfect for initial planning"
      ],
      popular: false,
      buttonText: "Start Free Discovery",
      buttonAction: () => setIsChatOpen(true)
    },
    {
      name: "1-Week Discovery Sprint",
      price: "₹75,000",
      period: "one-time",
      features: [
        "Everything in Free, plus:",
        "Human expert review & refinement",
        "Competitive analysis & market research",
        "Architecture design recommendations",
        "Risk assessment & mitigation plan",
        "Vendor/technology selection guidance",
        "2 strategy calls with our team",
        "Detailed cost & timeline estimates"
      ],
      popular: true,
      buttonText: "Book Discovery Sprint",
      buttonAction: () => window.location.href = '/book-call?service=sprint'
    },
    {
      name: "Full Implementation",
      price: "Custom",
      period: "project-based",
      features: [
        "Everything in Discovery Sprint",
        "Complete development & execution",
        "Dedicated project team",
        "Agile sprints with weekly updates",
        "Quality assurance & testing",
        "Deployment & training",
        "3-6 months post-launch support"
      ],
      popular: false,
      buttonText: "Get Custom Quote",
      buttonAction: () => window.location.href = '/book-call?service=strategy'
    }
  ];

  return (
    <>
      <Header />
      <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50">
        {/* Hero Section */}
        <section className="py-16 md:py-20">
          <div className="container-width px-4 md:px-8">
          <div className="text-center max-w-4xl mx-auto">
            <div className="inline-flex items-center gap-2 bg-gradient-to-r from-blue-600 to-purple-600 text-white px-4 py-2 rounded-full text-sm font-medium mb-6">
              <Zap className="w-4 h-4" />
              100% FREE: AI-Powered Requirements Discovery
            </div>
            
            <h1 className="text-5xl lg:text-6xl font-bold text-gray-900 mb-6 leading-tight">
              Get Your Project <span className="bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">Scope Document</span> for Free
            </h1>
            
            <p className="text-xl text-gray-600 mb-8 leading-relaxed">
              Start with our free AI discovery chat. Upgrade to expert-led Discovery Sprint or full implementation when you're ready.
            </p>
            
            <div className="flex flex-col sm:flex-row gap-4 justify-center mb-12">
              <Button 
                size="lg" 
                onClick={() => setIsChatOpen(true)}
                className="group bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 text-lg px-8 py-4"
              >
                Start Free Discovery Chat
                <ArrowRight className="w-5 h-5 ml-2 group-hover:translate-x-1 transition-transform" />
              </Button>
              
              <Button 
                variant="outline" 
                size="lg"
                onClick={generateSamplePDF}
                className="text-lg px-8 py-4 border-2 border-blue-600 text-blue-600 hover:bg-blue-50"
              >
                <FileText className="w-5 h-5 mr-2" />
                View Sample Document
              </Button>
            </div>
            
            {/* Trust Indicators */}
            <div className="flex flex-col sm:flex-row items-center justify-center gap-8 text-sm text-gray-600">
              <div className="flex items-center gap-2">
                <CheckCircle className="w-5 h-5 text-green-600" />
                <span>100% Free to Start</span>
              </div>
              <div className="flex items-center gap-2">
                <Clock className="w-5 h-5 text-blue-600" />
                <span>Get Results in 10 Minutes</span>
              </div>
              <div className="flex items-center gap-2">
                <Shield className="w-5 h-5 text-purple-600" />
                <span>No Credit Card Required</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-16 md:py-20 bg-white">
        <div className="container-width px-4 md:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">How It Works</h2>
            <p className="text-xl text-gray-600">Simple, fast, and accurate requirement discovery</p>
          </div>
          
          <div className="grid lg:grid-cols-3 gap-8">
            <div className="text-center">
              <div className="w-16 h-16 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-6">
                <MessageSquare className="w-8 h-8 text-blue-600" />
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-4">1. Chat with AI</h3>
              <p className="text-gray-600">Our AI asks guided questions about your project goals, timeline, budget, and technical requirements.</p>
            </div>
            
            <div className="text-center">
              <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-6">
                <FileText className="w-8 h-8 text-green-600" />
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-4">2. AI Generates Document</h3>
              <p className="text-gray-600">Instantly get a professional Scope of Work with timeline estimates, technology recommendations, and clear deliverables.</p>
            </div>
            
            <div className="text-center">
              <div className="w-16 h-16 bg-purple-100 rounded-full flex items-center justify-center mx-auto mb-6">
                <Zap className="w-8 h-8 text-purple-600" />
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-4">3. Start Your Project</h3>
              <p className="text-gray-600">Use the document to get accurate quotes, plan your project timeline, and kickstart development.</p>
            </div>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="py-16 md:py-20 bg-gray-50">
        <div className="container-width px-4 md:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">Why Choose AI Discovery?</h2>
            <p className="text-xl text-gray-600">Faster, more accurate, and comprehensive than traditional methods</p>
          </div>
          
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => (
              <div key={index} className="bg-white p-6 rounded-lg shadow-sm hover:shadow-md transition-shadow">
                <div className="mb-4">{feature.icon}</div>
                <h3 className="text-lg font-semibold text-gray-900 mb-2">{feature.title}</h3>
                <p className="text-gray-600 text-sm">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section className="py-16 md:py-20 bg-gray-900">
        <div className="container-width px-4 md:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-white mb-4">What Our Clients Say</h2>
            <p className="text-xl text-gray-300">Real feedback from real projects</p>
          </div>
          
          <div className="grid md:grid-cols-3 gap-8">
            {testimonials.map((testimonial, index) => (
              <div key={index} className="bg-gray-50 p-6 rounded-lg">
                <div className="flex mb-4">
                  {[...Array(testimonial.rating)].map((_, i) => (
                    <Star key={i} className="w-5 h-5 text-yellow-500 fill-current" />
                  ))}
                </div>
                <p className="text-gray-800 mb-4 italic">"{testimonial.text}"</p>
                <div>
                  <p className="font-semibold text-gray-900">{testimonial.name}</p>
                  <p className="text-sm text-gray-600">{testimonial.company}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section className="py-16 md:py-20 bg-gray-900">
        <div className="container-width px-4 md:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-white mb-4">From Free Discovery to Full Delivery</h2>
            <p className="text-xl text-gray-300">Start free, upgrade when you need expert help or full implementation</p>
          </div>
          
          <div className="grid lg:grid-cols-3 gap-8 max-w-6xl mx-auto">
            {pricingPlans.map((plan, index) => (
              <div key={index} className={`relative bg-white rounded-lg p-8 ${plan.popular ? 'ring-4 ring-blue-600' : ''}`}>
                {plan.popular && (
                  <div className="absolute -top-4 left-1/2 transform -translate-x-1/2 bg-blue-600 text-white px-4 py-2 rounded-full text-sm font-medium">
                    Most Popular
                  </div>
                )}
                
                <div className="text-center mb-8">
                  <h3 className="text-2xl font-bold text-gray-900 mb-2">{plan.name}</h3>
                  <div className="mb-4">
                    <span className="text-4xl font-bold text-gray-900">{plan.price}</span>
                    <span className="text-gray-600 ml-2">{plan.period}</span>
                  </div>
                </div>
                
                <ul className="space-y-4 mb-8">
                  {plan.features.map((feature, featureIndex) => (
                    <li key={featureIndex} className="flex items-start gap-3">
                      <CheckCircle className="w-5 h-5 text-green-600 mt-0.5 flex-shrink-0" />
                      <span className="text-gray-700">{feature}</span>
                    </li>
                  ))}
                </ul>
                
                <Button 
                  onClick={plan.buttonAction}
                  className={`w-full ${plan.popular ? 'bg-blue-600 hover:bg-blue-700' : 'bg-gray-900 hover:bg-gray-800'}`}
                  size="lg"
                >
                  {plan.buttonText}
                </Button>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-16 md:py-20 bg-gradient-to-r from-blue-600 to-purple-600">
        <div className="container-width px-4 md:px-8 text-center">
          <h2 className="text-4xl font-bold text-white mb-6">Ready to Define Your Project?</h2>
          <p className="text-xl text-blue-100 mb-8 max-w-2xl mx-auto">
            Start the AI-guided discovery process now and get your professional requirements document in minutes.
          </p>
          
          <Button 
            size="lg" 
            onClick={() => setIsChatOpen(true)}
            className="bg-white text-blue-600 hover:bg-gray-100 hover:text-blue-700 text-lg px-8 py-4 group font-semibold"
          >
            Start Discovery Chat
            <MessageSquare className="w-5 h-5 ml-2 group-hover:scale-110 transition-transform" />
          </Button>
        </div>
      </section>

      {/* Chat Interface */}
      <ChatBot isOpen={isChatOpen} onClose={() => setIsChatOpen(false)} />
    </div>
    <Footer />
    </>
  );
}
