'use client';

import React from 'react';
import { Download, FileText, Clock, DollarSign, Zap } from 'lucide-react';
import { Button } from '@/components/ui/button';

interface DocumentPreviewProps {
  projectData: {
    projectType?: string;
    businessGoals?: string;
    timeline?: string;
    budget?: string;
    techPreferences?: string;
    features?: string;
  };
  isVisible: boolean;
  onDownload: () => void;
}

export default function DocumentPreview({ projectData, isVisible, onDownload }: DocumentPreviewProps) {
  if (!isVisible) return null;

  const sampleData = {
    projectType: projectData.projectType || "Web Application",
    businessGoals: projectData.businessGoals || "Increase Revenue",
    timeline: projectData.timeline || "3-6 months",
    budget: projectData.budget || "₹2L - ₹5L",
    techPreferences: projectData.techPreferences || "React/Next.js",
    features: projectData.features || "User Authentication, Payment Processing"
  };

  return (
    <div className="bg-white border border-gray-200 rounded-lg p-6 shadow-lg">
      <div className="flex items-center gap-3 mb-6">
        <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center">
          <FileText className="w-6 h-6 text-blue-600" />
        </div>
        <div>
          <h3 className="text-lg font-semibold text-gray-900">Scope of Work Document</h3>
          <p className="text-sm text-gray-600">Generated by Kenkai Labs AI</p>
        </div>
      </div>

      <div className="space-y-4 mb-6">
        {/* Project Overview */}
        <div className="border-l-4 border-blue-600 pl-4">
          <h4 className="font-semibold text-gray-900 mb-2">Project Overview</h4>
          <p className="text-sm text-gray-700">
            Development of a {sampleData.projectType.toLowerCase()} focused on achieving {sampleData.businessGoals.toLowerCase()} 
            within a {sampleData.timeline.toLowerCase()} timeframe.
          </p>
        </div>

        {/* Key Metrics Grid */}
        <div className="grid grid-cols-2 gap-4">
          <div className="bg-gray-50 p-3 rounded-lg">
            <div className="flex items-center gap-2 mb-1">
              <Clock className="w-4 h-4 text-blue-600" />
              <span className="text-xs font-medium text-gray-600">TIMELINE</span>
            </div>
            <p className="text-sm font-semibold text-gray-900">{sampleData.timeline}</p>
          </div>
          
          <div className="bg-gray-50 p-3 rounded-lg">
            <div className="flex items-center gap-2 mb-1">
              <DollarSign className="w-4 h-4 text-green-600" />
              <span className="text-xs font-medium text-gray-600">BUDGET RANGE</span>
            </div>
            <p className="text-sm font-semibold text-gray-900">{sampleData.budget}</p>
          </div>
        </div>

        {/* Technical Stack */}
        <div className="border-l-4 border-green-600 pl-4">
          <h4 className="font-semibold text-gray-900 mb-2">Recommended Technology Stack</h4>
          <p className="text-sm text-gray-700">{sampleData.techPreferences}</p>
        </div>

        {/* Core Features */}
        <div className="border-l-4 border-purple-600 pl-4">
          <h4 className="font-semibold text-gray-900 mb-2">Core Features</h4>
          <p className="text-sm text-gray-700">{sampleData.features}</p>
        </div>

        {/* Estimated Effort */}
        <div className="bg-blue-50 p-4 rounded-lg">
          <div className="flex items-center gap-2 mb-2">
            <Zap className="w-5 h-5 text-blue-600" />
            <h4 className="font-semibold text-gray-900">Estimated Development Effort</h4>
          </div>
          <div className="grid grid-cols-3 gap-4 text-center">
            <div>
              <p className="text-lg font-bold text-blue-600">8-12</p>
              <p className="text-xs text-gray-600">Weeks</p>
            </div>
            <div>
              <p className="text-lg font-bold text-green-600">3-4</p>
              <p className="text-xs text-gray-600">Developers</p>
            </div>
            <div>
              <p className="text-lg font-bold text-purple-600">15-20</p>
              <p className="text-xs text-gray-600">Features</p>
            </div>
          </div>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="space-y-3">
        <Button onClick={onDownload} className="w-full bg-green-600 hover:bg-green-700">
          <Download className="w-4 h-4 mr-2" />
          Download Full Document (₹500)
        </Button>
        
        <div className="text-center">
          <p className="text-xs text-gray-500">
            Full document includes detailed timeline, milestones, risk assessment, and more
          </p>
        </div>
      </div>
    </div>
  );
}
